.TH PNGTOPI1 "1" "October 2017" "pngtopi1 @VERSION@" "User Commands"
.SH NAME
pngtopi1 \- PNG to Atari Degas (pi1...) and vice versa image converter
.SH SYNOPSIS
.B pngtopi1
[\fI\,OPTIONS\/\fR] \,<\fIinput.png\fR> [\,<\fIoutput\fR>]
.SS "OPTIONS:"
.TP
\fB\-h\fR \fB\-\-help\fR \fB\-\-usage\fR
Print this message and exit.
.TP
\fB\-V\fR \fB\-\-version\fR
Print version and copyright and exit.
.TP
\fB\-q\fR \fB\-\-quiet\fR
Print less messages.
.TP
\fB\-v\fR \fB\-\-verbose\fR
Print more messages.
.TP
\fB\-c\fR \fB\-\-color=XY\fR
Select color conversion method (see below).
.TP
\fB\-e\fR \fB\-\-ste\fR
Use STE color quantization (4 bits per component).
.TP
\fB\-z\fR \fB\-\-pcx\fR
Force output as a pc1, pc2 or pc3.
.TP
\fB\-r\fR \fB\-\-pix\fR
Force output as a pi1, pi2 or pi3.
.TP
\fB\-d\fR \fB\-\-same\-dir\fR
Automatic save path includes <\fIinput\fR> path.

.SH "DESCRIPTION"
A PNG/Degas image file converter.
.LP
When creating Degas image the <\fIinput\fR> image resolution is used
to select the <\fIoutput\fR> type.
.IP \[bu] 2
PI1 / PC1 images are 320x200x16 colors
.IP \[bu]
PI2 / PC2 images are 640x200x4 colors
.IP \[bu]
PI3 / PC3 images are 640x400x2 monochrome (B&W)

.SS "Output type"
.IP \[bu] 2
If \fB--pix \fR or \fB--pcx \fR is specified the \fIoutput\fR is
respectively a raw (PI?) or RLE compressed (PC?) Degas image whatever
the \fIinput\fR is.
.IP \[bu]
If \fIinput\fR is a \fBPNG \fR image the default is to create a PI?
image unless a provided \fIoutput\fR suggest otherwise.
.IP \[bu]
If \fIinput\fR is a Degas image the default is to create a \PNG image
unless a provided \fIoutput\fR suggest otherwise.
.IP \[bu]
If \fBpngtopi1 \fR detects a discrepancy between a provided
\fIoutput\fR filename extension and what is really going to be written
then it issues a warning but still process as requested. Use \fB-q\fR
to remove the warning.

.SS "Color conversion mode"
.IP \[bu] 2
The \fBX\fR parameter decides if a Degas image will use 3 or 4 bits
per color component.  The consequence might be the lost of a precious
colormap entry in some (rare) cases if the provided input image was
not created accordingly.
.IP \[bu]
The \fBY\fR parameter picks the method used to upscale 3/4 bits color
component to 8 bits.
.RS 2
.IP \[bu] 2
\fBz\fR Simple Left shifting br \fB$3 -> 3:$60 4:$60\fR
.IP \[bu]
\fBr\fR Replicating left bits \fB$3 -> 3:$6C 4:$66\fR
.IP \[bu]
\fBf\fR Using the full range \fB$3 -> 3:$6D 4:$66\fR
.RE
.mso www.tmac
.SH "REPORTING BUGS"
Report bugs at
.URL "https://github.com/benjihan/pngtopi1/issues" "pngtopi1 on github"
.SH "COPYRIGHT"
Copyright \(co 2017-2023 Benjamin Gerard AKA Ben^OVR
.br
Licensed under GNU General Public License 3
